BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Champion] (
    [id] INT NOT NULL IDENTITY(1,1),
    [biography] NVARCHAR(1000) NOT NULL,
    [release_date] DATETIME2 NOT NULL,
    CONSTRAINT [Champion_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
